### ISSUE TITLE
Minor bugs in tutorial(s)

### ISSUE THREAD

**Issue by ammaraziz** [nextstrain/zika-tutorial#3]
Hi everyone,

Not sure if this is a great time to be submitting tutorial updates/fixes so I thought I'd ask. I'm familarising myself with augur/auspice via the  tutorials. I've come across a few minor errors in the Zika tutorial due to differences in versions (I'm guess pre and post v5 differences). 

Example:

`augur translate 
  --tree results/tree.nwk 
  --ancestral-sequences results/nt_muts.json 
  --reference-sequence config/zika_outgroup.gb 
  --output results/aa_muts.json`

Will produce this very helpful error:

> augur ancestral: error: ambiguous option: --output could match --output-node-data, --output-sequences, --output-vcf

With the correct flag being:

`--output-node-data results/aa_muts.json`

There's one more minor error I came across. 

Let me know,

Ammar

**Comment by eharkins** [comment]
Hi @ammaraziz, I've updated the tutorial (https://github.com/nextstrain/docs.nextstrain.org/commit/4b47a1123103da4994cfc7c8c5be590f75f09125) so it should be correct at https://docs.nextstrain.org/en/latest/tutorials/zika.html. Thanks for raising this issue and let us know if you still have this error or any other issues!
