### ISSUE TITLE
error: ambiguous option

### ISSUE THREAD

**Issue by nitha26** [nextstrain/zika-tutorial#4]
Hi,
When i run ``Infer Ancestral Sequences`` getting following error  
``[localhost zika-tutorial]# augur ancestral --tree results/tree.nwk --alignment results/aligned.fasta --output results/nt_muts.json --inference joint``
  
augur ancestral: error: ambiguous option: --output could match --output-node-data, --output-sequences, --output-vcf

Could you point me where i am doing wrong.

Thanks

**Comment by nitha26** [comment]
I think the error because when we just given only ``--output``. I have crossed checked the ``augur ancestral`` command line and modified the command line to ``augur ancestral --tree results/tree.nwk --alignment results/aligned.fasta -output-node-data results/nt_muts.json --inference joint`` it worked.

Whether it is correct?

**Comment by eharkins** [comment]
That's correct @nitha26, sorry for not responding earlier. I've updated the tutorial here https://github.com/nextstrain/docs.nextstrain.org/commit/4b47a1123103da4994cfc7c8c5be590f75f09125 so it should be updated at https://docs.nextstrain.org/en/latest/tutorials/zika.html. Thanks for raising this issue!
