### ISSUE TITLE
colors: differences between tutorial and live build

### ISSUE THREAD

**Issue by j23414** [nextstrain/zika-tutorial#9]
### Current Behavior

This might not be a bug exactly but there's inconsistent coloring of invariant regions in the zika-tutorial tree vs the live builds. A user brought up that they expected our zika-tutorial to behave similar to the zika build, just with subsetted data, which kicked off the need to explain why and how they were different.

**Zika-Tutorial**

```
git clone https://github.com/nextstrain/zika-tutorial.git
cd zika-tutorial
nextstrain build . -cores 1
nextstrain view auspice
```
<img width="1091" alt="Screen Shot 2022-10-01 at 12 02 14 PM" src="https://user-images.githubusercontent.com/1077254/193424452-9ab1c7c9-4401-4b98-8e12-cd59e5b825a9.png">

**Zika build**

```
git clone https://github.com/nextstrain/zika.git
cd zika
nextstrain build . -cores 1
nextstrain view auspice
# pushing to live site code...
```

https://next.nextstrain.org/zika?c=gt-ENV_50

<img width="1092" alt="Screen Shot 2022-10-01 at 12 01 03 PM" src="https://user-images.githubusercontent.com/1077254/193424578-bd74a4c0-fb10-4bc5-97a5-83ff2576ad60.png">

### Expected behavior

Same behavior between zika_tutorial and zika. 

### Possible solution

Maybe we should copy the Snakemake file from zika to zika_tutorial (`augur export` and flags seem to have diverged). The zika Snakemake will take the tutorial's example `data/sequences.fasta` and `data/metadata.tsv` and bypass any database download rules. 

However, I can also see how the tutorial's Snakemake should be consistent with the tutorial documentation at:

* https://docs.nextstrain.org/en/latest/tutorials/creating-a-workflow.html

and the extra download rules might be confusing for someone just starting to learn the commands. Hmm...

I'm still exploring what exactly caused the different behavior, so just surfacing the discussion here. 

### Your environment: 
 - Operating system: MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports), MacOS Montary
 - Browser: Google Chrome
 - Version (e.g. `auspice 2.7.0`): `nextstrain --version` -> `nextstrain.cli 3.0.6`

**Comment by jameshadfield** [comment]
>  inconsistent coloring of invariant regions in the zika-tutorial tree vs the live builds

Genotypes with no observed mutations can only be coloured with the optional `_root-sequence.json` sidecar file. Without this we have no way of knowing what the base is at this position. I'd support adding this to the tutorial build.

**Comment by j23414** [comment]
Thanks @jameshadfield ! Adding the `--include-root-sequence` flag to `augur export v2` worked great: 

![Screen Shot 2022-10-07 at 10 05 12 AM](https://user-images.githubusercontent.com/1077254/194614651-e9935d77-18c0-4dc2-88aa-6f9b21cef23e.png)

PR is ready for review at: https://github.com/nextstrain/zika-tutorial/pull/10
